version: "3.7"

volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:
  vote:
    image: tblandford/lfd261-vote:v2
    ports: 
      - 5000:80
    # links:
      # - redis:redis
    depends_on:
      - redis
    networks:
      - instavote

  redis:
    image: redis:alpine
    networks:
      - instavote
  
  db:
    image: postgres:9.4
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - instavote
  
  result:
    image: tblandford/lfd261-result:v13
    ports:
      - 5001:4000
    # links:
    #   - db:db
    depends_on:
      - redis
    networks:
      - instavote

  worker:
    image: tblandford/lfd261-worker:v20
    # links:
    #   - redis:redis
    #   - db:db
    depends_on:
      - db
      - redis
    networks:
      - instavote